## Домашнее задание 1
### Основы Python и пакет NumPy
---


In [1]:
import numpy as np
import random
import scipy.stats as sps

### Задача 1
В первой задаче вам предлагается перемножить две матрицы двумя способами -- без использования пакета ***numpy*** и с ним. Использовать матричное произведение.

In [ ]:
# Для генерации матриц используем фукнцию random -- она используется для генерации случайных объектов 
# функция sample создает случайную выборку. В качестве аргумента ей передается кортеж (i,j), здесь i -- число строк,
# j -- число столбцов.
a = np.random.sample((100,1000))
b = np.random.sample((1000,100))
# выведите размерность (ранг) каждой матрицы с помощью функции ndim.
# Используйте функцию shape, что она вывела?
# ========
# тут можно писать код 
# ========

In [ ]:
#ndim + shape tests
#a.ndim
#b.ndim
#a.shape
#b.shape

#a = np.random.sample((3,4))
#b = np.random.sample((4,3))
#print(a)
#print(b)

[[0.3103252  0.58755198 0.70857875 0.1092055 ]
 [0.8867744  0.63975632 0.09588785 0.58387453]
 [0.88423348 0.5973159  0.04487722 0.51555617]]
[[0.30236085 0.06967024 0.35327718]
 [0.21631774 0.89525523 0.39402382]
 [0.32812541 0.38740462 0.88772258]
 [0.86631622 0.95236478 0.65520883]]


In [ ]:
#def np_mult(a, b):
    # здесь напишите перемножение матриц с
    # использованием NumPy и выведите результат
def mult(a,b):
  c = []
  for i in range(0,len(a)):
      temp=[]
      for j in range(0,len(b[0])):
          s = 0
          for k in range(0,len(a[0])):
              s += a[i][k]*b[k][j]
          temp.append(s)
      c.append(temp)
  return c
mult(a,b)

[[234.66484121119476,
  230.90661935364827,
  239.53166315770966,
  239.3830274744539,
  241.54367084103268,
  229.4652404040549,
  238.59295387218384,
  235.7806586601126,
  238.46077466656524,
  236.73163067365064,
  230.75535674579723,
  245.86110241343124,
  245.05044020429963,
  246.7428098886003,
  239.28728158193962,
  240.4590693115838,
  239.57955118482332,
  240.33919622633266,
  232.33179237985186,
  233.0318471216422,
  240.34657958541547,
  238.42197706804944,
  238.12378391981062,
  248.12580501584065,
  240.93168362851745,
  233.2171871684758,
  243.42563299704196,
  243.57487195128317,
  239.36891005787606,
  238.19303239141433,
  235.43504405564946,
  244.38582392395742,
  237.47072302578943,
  239.2057938836853,
  249.74360472990156,
  251.80996858458835,
  240.97796230750126,
  244.9001287079703,
  234.73582391963853,
  244.21425382550265,
  244.38849129317802,
  238.95087102102917,
  236.8466889643508,
  234.01729244573394,
  243.11750569067945,
  225.34999751779276

In [ ]:
def np_mult(a, b):
    # здесь напишите перемножение матриц с
    # использованием NumPy и выведите результат
    return np.dot(a,b)
np_mult(a,b)

array([[234.66484121, 230.90661935, 239.53166316, ..., 236.23420611,
        240.76814506, 233.03109048],
       [244.32478362, 251.59157802, 253.6173638 , ..., 242.79970838,
        245.23955132, 245.53860646],
       [243.18046668, 246.22687528, 249.85630584, ..., 251.19072773,
        252.59116571, 246.37711037],
       ...,
       [238.08566754, 241.43565605, 247.60277368, ..., 240.35941629,
        247.03101826, 243.04879754],
       [245.57613285, 246.89367715, 255.07601215, ..., 246.60880227,
        247.18955845, 244.65166716],
       [240.92578198, 241.93446284, 246.96628177, ..., 241.75461849,
        243.67931311, 243.27495745]])

In [ ]:
# Превратим матрицы в листы, чтобы протестировать функцию без np
a_list = [[x for x in row] for row in a]
b_list = [[x for x in row] for row in b]

In [ ]:
%%time
# засечем время работы функции без NumPy
mult(a_list, b_list)

CPU times: user 4.16 s, sys: 4.7 ms, total: 4.17 s
Wall time: 4.17 s


[[249.22623744935558,
  238.7266170324807,
  245.520056879244,
  245.58021353105778,
  234.29668948723562,
  247.41305100420112,
  250.60758482453576,
  253.8876570475457,
  252.55352004975887,
  243.22498309000278,
  240.48944873787644,
  242.50556615124881,
  242.98279239741447,
  241.50289901054683,
  243.16927262926566,
  252.5691438886566,
  243.23951973948328,
  245.36899661157676,
  250.4001118649033,
  233.970612850586,
  245.66918150679092,
  247.36804578072184,
  244.44196783080608,
  244.52012643017792,
  242.86862522918943,
  246.53387252278418,
  242.05848704314724,
  248.1757589003964,
  251.41506167534655,
  241.86087691175555,
  239.46618481107026,
  247.8567071703513,
  241.60261099111315,
  246.1381639884269,
  231.9661871276183,
  245.2164965338098,
  248.63490629282708,
  243.71669854004563,
  239.9386372383442,
  252.8074478612411,
  243.57833047710216,
  237.81990519445083,
  240.84002444401233,
  231.37352771816967,
  243.08210409122125,
  242.51028533907592,
  2

In [ ]:
%%time
# засечем время работы функции с NumPy
np_mult(a, b)

CPU times: user 1.04 ms, sys: 2.01 ms, total: 3.05 ms
Wall time: 2.28 ms


array([[249.22623745, 238.72661703, 245.52005688, ..., 240.45000992,
        239.64646903, 236.49078895],
       [243.23383664, 243.38429109, 244.90553389, ..., 235.52161245,
        239.9167465 , 229.3389485 ],
       [256.3095269 , 245.39979463, 258.48530603, ..., 246.06142901,
        243.28505693, 248.79208329],
       ...,
       [255.75766634, 244.11320657, 249.49157925, ..., 245.68660562,
        243.14391014, 242.50545748],
       [257.81113459, 254.46532468, 261.30278257, ..., 247.35211632,
        250.92587301, 247.40743609],
       [255.38750529, 249.82775663, 247.37347354, ..., 250.69606429,
        244.36658066, 242.37959441]])

### Задача 2
Напишите функцию, которая по данной последовательности $\{A_i\}_{i=1}^n$ строит последовательность $S_n$, где $S_k = \frac{A_1 + ... + A_k}{k}$.  
Аналогично -- с помощью библиотеки **NumPy** и без нее. Сравните скорость, объясните результат.

In [106]:
# функция, решающая задачу с помощью NumPy
import numpy as np
testlst=list(range(1, 6)) #test array

def sec_av(A):
  return np.cumsum(A)
print(testlst)
sec_av(testlst)

[1, 2, 3, 4, 5]


array([ 1,  3,  6, 10, 15])

In [128]:
# функция без NumPy
A=list(range(1, 6)) #test array

#не работает на большом массиве
def stupid_sec_av(A):
  cumsum=[]
  iter=0
  for i in A:
    cumsum.append(sum(A[:iter+1]))
    iter+=1
  return cumsum
print(A)  
print(stupid_sec_av_oldway(A))


[1, 2, 3, 4, 5]
[1, 3, 6, 10, 15]


In [112]:
a=list(range(1, 6)) #test array
cumsum = [sum(a[:i+1]) for i in range(len(a))] 
print(cumsum)

[1, 3, 6, 10, 15]


In [130]:
# функция без NumPy
#def stupid_sec_av(A):
    # Ваш код здесь

# зададим некоторую последовательность и проверим ее на ваших функциях. 
# Первая функция должна работать ~ в 50 раз быстрее
A = sps.uniform.rvs(size=10 ** 4) 
A_list = list(A)

%time S1 = sec_av(A)
%time S2 = stupid_sec_av(A_list)
#проверим корректность:
np.abs(S1 - S2).sum()

CPU times: user 103 µs, sys: 1 µs, total: 104 µs
Wall time: 110 µs
CPU times: user 4.47 s, sys: 12.8 ms, total: 4.48 s
Wall time: 4.49 s


0.0

### Задача 3

Пусть задан некоторый массив $X$. Надо построить новый массив, где все элементы с нечетными индексами требуется заменить на число $a$ (если оно не указано, то на 1). Все элементы с четными индексами исходного массива нужно возвести в куб и записать в обратном порядке относительно позиций этих элементов. Массив $X$ при этом должен остаться без изменений. В конце требуется слить (конкатенировать) массив X с преобразованным X и вывести в обратном порядке. 

In [ ]:
# функция, решающая задачу с помощью NumPy
def transformation(X, a=1):
    # Ваш код здесь
    return Y

In [ ]:
# функция, решающая задачу  без NumPy
def stupid_transformation(X, a=1):
    # Ваш код здесь
    return Y

In [ ]:
# функция, решающая задачу  без NumPy
def stupid_transformation(X, a=1):
  arr=X.copy()
  arreven=X[::-2]
  arreven=[item**3 for item in arreven] 
  evenidx=0
  for idx in range(len(arr)):
    if (idx%2!=0):
      arr[idx]=a
      evenidx+=1
    else:
      arr[idx]=arreven[evenidx]

  arrconcat=X+arr    
  return arrconcat[::-1]

#test
arrtst=[0,1,0,2,0,3]
stupid_transformation(arrtst,a=9999)

[9999, 1, 9999, 2, 9999, 3, 3, 0, 2, 0, 1, 0]

In [ ]:
# функция, решающая задачу  без NumPy
def stupid_transformation(X, a=1):
  arr =X.copy()
  arreven=X[::2]
  arreven=[i**3 for i in arreven] 
  arr[::2]=arreven[::-1]
  arodd=arr[1::2] 
  arodd=[a for item in arodd] 
  arr[1::2]=arodd
  res=X+arr
  return res[::-1]
arrtst=[2,0,4,0,6,0]
stupid_transformation(arrtst,a=9999)


[9999, 8, 9999, 64, 9999, 216, 0, 6, 0, 4, 0, 2]

In [ ]:
#зачем оборачивать нампай массив еще раз в функцию np.array? Зачем еще раз делать копию? Не вижу сравнения скоростей работы с и без

# функция, решающая задачу с NumPy
def transformation(X, a=1):
  #old =np.array(X) #убрал ненужную строку, т.к. я и так делаю копию исх.массива
  arr =np.array(X.copy()) #оборачиваю в np.array, чтобы сделать умножение каждого элемента
  arr[::2]**=3 
  arr[1::2]=a
  arreven=arr[::2]
  arr[::2]=arreven[::-1]
  res=np.concatenate((X, arr))
  return res[::-1]
arrtst=[2,0,4,0,6,0]

#check
stupid_transformation(arrtst,a=9999)

#array([9999,    8, 9999,   64, 9999,  216,    0,    6,    0,    4,    0,
#          2])


array([9999,    8, 9999,   64, 9999,  216,    0,    6,    0,    4,    0,
          2])

In [ ]:
X = sps.uniform.rvs(size=10 ** 3)
X_list = list(X)
# здесь код эффективнее примерно в 20 раз. 
# если Вы вдруг соберетесь печатать массив без np -- лучше сначала посмотрите на его размер
%time S1 = transformation(X)
%time S2 = stupid_transformation(X_list)
# проверим корректность:
print(np.abs(S1 - S2).sum())

CPU times: user 156 µs, sys: 0 ns, total: 156 µs
Wall time: 162 µs
CPU times: user 439 µs, sys: 0 ns, total: 439 µs
Wall time: 446 µs
0.0


Почему методы ***numpy*** оказываются эффективнее?

In [ ]:
# Ваш ответ
Разница в 2.75 раза
Numpy, как и большинство других питоновских либ, написаны на C, вызываясь питоном в качестве API. 
Классический код на питоне исполняются интерпретатором, что несравнимо по скорости со скомпилированным исполняемым кодом.

## Дополнительные задачи

Дополнительные задачи подразумевают, что Вы самостоятельно разберётесь в некоторых функциях ***numpy***, чтобы их сделать, но в то же время не являются обязательными.

### Задача 4*

Дана функция двух переменных: $f(x, y) = sin(x)cos(y)$ (это просто такой красивый 3D-график), а также дана функция для отрисовки $f(x, y)$ (`draw_f()`), которая принимает на вход двумерную сетку, на которой будет вычисляться функция.  

Вам нужно разобраться в том, как строить такие сетки (подсказка - это одна конкретная функция ***numpy***), и подать такую сетку на вход функции отрисовки.

In [ ]:
from matplotlib import pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
%matplotlib inline

def f(x, y):
    '''Функция двух переменных'''
    return np.sin(x) * np.cos(y)

def draw_f(grid_x, grid_y):
    '''Функция отрисовки функции f(x, y)'''
    fig = plt.figure(figsize=(10, 8))
    ax = Axes3D(fig)
    ax.plot_surface(grid_x, grid_y, f(grid_x, grid_y), cmap='inferno')
    plt.show()

In [ ]:
grid_x, grid_y = # Ваш ответ

draw_f(grid_x, grid_y)

### Задача 5*

Вам дана картинка. При загрузке её размерность равна 3: **(w, h, num_channels)**, где **w** - ширина картинки в пикселях, **h** - высота картинки в пикселях, **num_channels** - количество каналов *(R, G, B, alpha)*.

Вам нужно "развернуть" картинку в одномерный массив размера w \* h \* num_channels, написав **одну строку кода**.

In [ ]:
from matplotlib import pyplot as plt
%matplotlib inline

Загрузим картинку. Если эта ячейка не сработает, смотрите дальше:

In [ ]:
path_to_image = './image.jpg'
image_array = plt.imread(path_to_image)

Если Вы работаете в google colab или по каким-то еще причинам картинка с диска не загрузилась, можно попробовать загрузить через ссылку в интернете:

In [ ]:
from PIL import Image
import requests
from io import BytesIO

path_to_image = '__enter your image URL here__'
# например: https://github.com/hocop/sberbank_madmo/raw/master/day_1/homework/image.jpg

response = requests.get(path_to_image)
img = Image.open(BytesIO(response.content))

image_array = np.array(img)

В любом случае, у Вас должен появиться объект `image_array`.  
Распечатаем его на экране:

In [ ]:
plt.imshow(image_array);

In [ ]:
# Ваш код здесь

In [ ]:
# Здесь выведите размерность нового массива