## Домашнее задание 1
### Основы Python и пакет NumPy
---


In [49]:
import numpy as np
import random
import scipy.stats as sps

### Задача 1
В первой задаче вам предлагается перемножить две матрицы двумя способами -- без использования пакета ***numpy*** и с ним. Использовать матричное произведение.

In [ ]:
# Для генерации матриц используем фукнцию random -- она используется для генерации случайных объектов 
# функция sample создает случайную выборку. В качестве аргумента ей передается кортеж (i,j), здесь i -- число строк,
# j -- число столбцов.
a = np.random.sample((100,1000))
b = np.random.sample((1000,100))
# выведите размерность (ранг) каждой матрицы с помощью функции ndim.
# Используйте функцию shape, что она вывела?
# ========
# тут можно писать код 
# ========

In [ ]:
#ndim + shape tests
a.ndim
b.ndim
a.shape
b.shape

array([[23.75982937, 23.7816418 , 23.73256053, 25.27094675, 28.70704667,
        23.78161478, 25.33098606, 26.61332518, 26.42458733, 25.32229965],
       [24.56474594, 25.37180579, 25.07889699, 27.63394212, 26.25133495,
        25.44925512, 25.73995263, 26.60445524, 26.9007609 , 25.49249584],
       [23.05681274, 23.77903745, 25.5151748 , 25.17485068, 26.59150676,
        24.5285865 , 23.91411125, 25.18567394, 25.22098325, 23.22832109],
       [22.56209586, 22.92137885, 24.58535722, 26.48526741, 26.45952766,
        23.85128913, 25.43267693, 25.03076111, 24.88786365, 26.25939731],
       [26.73955135, 28.53999386, 28.5126405 , 30.88564366, 29.24300983,
        27.12686417, 29.14136509, 30.91741625, 29.60122439, 29.59350814],
       [21.34271929, 22.81990114, 21.45205871, 24.5539887 , 24.07876261,
        21.4525195 , 23.06818466, 23.64452208, 22.45176251, 23.68136878],
       [25.64334117, 24.6045571 , 26.38113829, 29.1126805 , 28.17103136,
        26.82447213, 27.35013843, 29.43993828

In [ ]:
def np_mult(a, b):
    # здесь напишите перемножение матриц с
    # использованием NumPy и выведите результат
    return np.dot(a,b)
np_mult(a,b)

array([[255.02788709, 250.28218658, 252.50621586, ..., 253.86973555,
        258.6636907 , 255.48011751],
       [244.98650246, 246.70666763, 253.6322028 , ..., 253.79703809,
        254.97837975, 254.23302046],
       [242.33280131, 238.58418391, 248.10256205, ..., 250.8038926 ,
        254.957914  , 252.29041521],
       ...,
       [245.55664975, 248.30536005, 251.8225555 , ..., 254.57052714,
        254.41386736, 255.80916937],
       [244.75557811, 242.45416833, 242.39500612, ..., 247.83231113,
        246.39921996, 249.54851826],
       [254.65446358, 254.45449847, 259.72414814, ..., 251.90747978,
        255.10080479, 256.112332  ]])

In [ ]:
# Превратим матрицы в листы, чтобы протестировать функцию без np
a_list = [[x for x in row] for row in a]
b_list = [[x for x in row] for row in b]

In [ ]:
%%time
# засечем время работы функции без NumPy
mult(a_list, b_list)

In [ ]:
%%time
# засечем время работы функции с NumPy
np_mult(a, b)

CPU times: user 3.38 ms, sys: 1.09 ms, total: 4.48 ms
Wall time: 6.42 ms


array([[255.02788709, 250.28218658, 252.50621586, ..., 253.86973555,
        258.6636907 , 255.48011751],
       [244.98650246, 246.70666763, 253.6322028 , ..., 253.79703809,
        254.97837975, 254.23302046],
       [242.33280131, 238.58418391, 248.10256205, ..., 250.8038926 ,
        254.957914  , 252.29041521],
       ...,
       [245.55664975, 248.30536005, 251.8225555 , ..., 254.57052714,
        254.41386736, 255.80916937],
       [244.75557811, 242.45416833, 242.39500612, ..., 247.83231113,
        246.39921996, 249.54851826],
       [254.65446358, 254.45449847, 259.72414814, ..., 251.90747978,
        255.10080479, 256.112332  ]])

### Задача 2
Напишите функцию, которая по данной последовательности $\{A_i\}_{i=1}^n$ строит последовательность $S_n$, где $S_k = \frac{A_1 + ... + A_k}{k}$.  
Аналогично -- с помощью библиотеки **NumPy** и без нее. Сравните скорость, объясните результат.

In [ ]:
# функция, решающая задачу с помощью NumPy
def sec_av(A):
    # Ваш код здесь

In [53]:
# функция, решающая задачу с помощью NumPy
import numpy as np
testlst=list(range(1, 6)) #test array

def sec_av(A):
  res=[]
  for idx, x in np.ndenumerate(A):
    res.append( sum(A[:idx[0]+1]) )
  return res  
print(testlst)
sec_av(testlst)

[1, 2, 3, 4, 5]


[1, 3, 6, 10, 15]

In [52]:
# функция без NumPy
testlst=list(range(1, 6)) #test array

def stupid_sec_av(A):
  np.array(A)
  num=1
  res=[]
  for i in lst:    
    numadd=sum(lst[:num])
    res.append(numadd)
    num+=1
  return res
print(testlst)
stupid_sec_av(testlst)
    
    

[1, 2, 3, 4, 5]


[1, 3, 6, 10, 15]

In [55]:
# функция без NumPy
#def stupid_sec_av(A):
    # Ваш код здесь

# зададим некоторую последовательность и проверим ее на ваших функциях. 
# Первая функция должна работать ~ в 50 раз быстрее
A = sps.uniform.rvs(size=10 ** 6) 
A_list = list(A)

%time S1 = sec_av(A)
%time S2 = stupid_sec_av(A_list)
#проверим корректность:
np.abs(S1 - S2).sum()

### Задача 3

Пусть задан некоторый массив $X$. Надо построить новый массив, где все элементы с нечетными индексами требуется заменить на число $a$ (если оно не указано, то на 1). Все элементы с четными индексами исходного массива нужно возвести в куб и записать в обратном порядке относительно позиций этих элементов. Массив $X$ при этом должен остаться без изменений. В конце требуется слить (конкатенировать) массив X с преобразованным X и вывести в обратном порядке. 

In [ ]:
# функция, решающая задачу с помощью NumPy
def transformation(X, a=1):
    # Ваш код здесь
    return Y

In [ ]:
# функция, решающая задачу  без NumPy
def stupid_transformation(X, a=1):
    # Ваш код здесь
    return Y

In [ ]:
# функция, решающая задачу  без NumPy
def stupid_transformation(X, a=1):
  arr=X.copy()
  arreven=X[::-2]
  arreven=[item**3 for item in arreven] 
  evenidx=0
  for idx in range(len(arr)):
    if (idx%2!=0):
      arr[idx]=a
      evenidx+=1
    else:
      arr[idx]=arreven[evenidx]

  arrconcat=X+arr    
  return arrconcat[::-1]

arrtst=[0,1,0,2,0,3]
stupid_transformation(arrtst,a=9999)

[9999, 1, 9999, 2, 9999, 3, 3, 0, 2, 0, 1, 0]

In [ ]:
# функция, решающая задачу  без NumPy
def stupid_transformation(X, a=1):
  arr =X.copy()
  arreven=X[::2]
  arreven=[i**3 for i in arreven] 
  arr[::2]=arreven[::-1]
  arodd=arr[1::2] 
  arodd=[a for item in arodd] 
  arr[1::2]=arodd
  res=X+arr
  return res[::-1]
arrtst=[2,0,4,0,6,0]
stupid_transformation(arrtst,a=9999)


[9999, 8, 9999, 64, 9999, 216, 0, 6, 0, 4, 0, 2]

In [ ]:
# функция, решающая задачу с NumPy
def stupid_transformation(X, a=1):
  old =np.array(X)
  arr =np.array(X).copy()
  arr[::2]**=3 
  arr[1::2]=a
  arreven=arr[::2]
  arr[::2]=arreven[::-1]
  res=np.concatenate((old, arr))
  return res[::-1]
arrtst=[2,0,4,0,6,0]
stupid_transformation(arrtst,a=9999)



array([9999,    8, 9999,   64, 9999,  216,    0,    6,    0,    4,    0,
          2])

In [ ]:
X = sps.uniform.rvs(size=10 ** 3)
X_list = list(X)
# здесь код эффективнее примерно в 20 раз. 
# если Вы вдруг соберетесь печатать массив без np -- лучше сначала посмотрите на его размер
%time S1 = transformation(X)
%time S2 = stupid_transformation(X_list)
# проверим корректность:
print(np.abs(S1 - S2).sum())

Почему методы ***numpy*** оказываются эффективнее?

In [ ]:
# Ваш ответ
Numpy, как и большинство других либ, написаны на C, вызываясь питоном в качестве API. 
Классический код на питоне исполняются интерпретатором, что несравнимо по скорости со скомпилированным исполняемым кодом.

## Дополнительные задачи

Дополнительные задачи подразумевают, что Вы самостоятельно разберётесь в некоторых функциях ***numpy***, чтобы их сделать, но в то же время не являются обязательными.

### Задача 4*

Дана функция двух переменных: $f(x, y) = sin(x)cos(y)$ (это просто такой красивый 3D-график), а также дана функция для отрисовки $f(x, y)$ (`draw_f()`), которая принимает на вход двумерную сетку, на которой будет вычисляться функция.  

Вам нужно разобраться в том, как строить такие сетки (подсказка - это одна конкретная функция ***numpy***), и подать такую сетку на вход функции отрисовки.

In [ ]:
from matplotlib import pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
%matplotlib inline

def f(x, y):
    '''Функция двух переменных'''
    return np.sin(x) * np.cos(y)

def draw_f(grid_x, grid_y):
    '''Функция отрисовки функции f(x, y)'''
    fig = plt.figure(figsize=(10, 8))
    ax = Axes3D(fig)
    ax.plot_surface(grid_x, grid_y, f(grid_x, grid_y), cmap='inferno')
    plt.show()

In [ ]:
grid_x, grid_y = # Ваш ответ

draw_f(grid_x, grid_y)

### Задача 5*

Вам дана картинка. При загрузке её размерность равна 3: **(w, h, num_channels)**, где **w** - ширина картинки в пикселях, **h** - высота картинки в пикселях, **num_channels** - количество каналов *(R, G, B, alpha)*.

Вам нужно "развернуть" картинку в одномерный массив размера w \* h \* num_channels, написав **одну строку кода**.

In [ ]:
from matplotlib import pyplot as plt
%matplotlib inline

Загрузим картинку. Если эта ячейка не сработает, смотрите дальше:

In [ ]:
path_to_image = './image.jpg'
image_array = plt.imread(path_to_image)

Если Вы работаете в google colab или по каким-то еще причинам картинка с диска не загрузилась, можно попробовать загрузить через ссылку в интернете:

In [ ]:
from PIL import Image
import requests
from io import BytesIO

path_to_image = '__enter your image URL here__'
# например: https://github.com/hocop/sberbank_madmo/raw/master/day_1/homework/image.jpg

response = requests.get(path_to_image)
img = Image.open(BytesIO(response.content))

image_array = np.array(img)

В любом случае, у Вас должен появиться объект `image_array`.  
Распечатаем его на экране:

In [ ]:
plt.imshow(image_array);

In [ ]:
# Ваш код здесь

In [ ]:
# Здесь выведите размерность нового массива